idem
git-svn-id: https://svn.ninux.org/svn/ninuxdeveloping/packages@780 ef3c9aa7-e928-0410-9a28-8491e62b674b

diff --git a/stackless/patches/100-cross-compile.patch b/stackless/patches/100-cross-compile.patch
--- a/stackless/patches/100-cross-compile.patch
+++ b/stackless/patches/100-cross-compile.patch
@@ -19,6 +19,24 @@ diff -Nur python-2.6.2-stackless-orig/configure python-2.6.2-stackless/configure
  else
    cat >conftest.$ac_ext <<_ACEOF
  /* confdefs.h.  */
+@@ -17158,7 +17158,7 @@
+ See \`config.log' for more details." >&5
+ echo "$as_me: error: cannot run test program while cross compiling
+ See \`config.log' for more details." >&2;}
+-   { (exit 1); exit 1; }; }
++   }
+ else
+   cat >conftest.$ac_ext <<_ACEOF
+ /* confdefs.h.  */
+@@ -24357,7 +24357,7 @@
+ See \`config.log' for more details." >&5
+ echo "$as_me: error: cannot run test program while cross compiling
+ See \`config.log' for more details." >&2;}
+-   { (exit 1); exit 1; }; }
++   }
+ else
+   cat >conftest.$ac_ext <<_ACEOF
+ /* confdefs.h.  */
 diff -Nur python-2.6.2-stackless-orig/configure python-2.6.2-stackless/configure
 --- python-2.6.2-stackless-orig/Makefile.pre.in	2010-05-20 17:33:32.989078907 +0200
 +++ python-2.6.2-stackless/Makefile.pre.in	2010-05-20 17:37:52.429050922 +0200
