Updated olsrd-ninux package to latest upstream changes from olsrd and openwrt
This package compiles olsrd from the latest git stable of the olsrd repository



git-svn-id: https://svn.ninux.org/svn/ninuxdeveloping/packages@935 ef3c9aa7-e928-0410-9a28-8491e62b674b

diff --git a/olsrd-ninux/files/olsrd.init b/olsrd-ninux/files/olsrd.init
--- a/olsrd-ninux/files/olsrd.init
+++ b/olsrd-ninux/files/olsrd.init
@@ -1,12 +1,13 @@
 #!/bin/sh /etc/rc.common
 # Copyright (C) 2008  Alina Friedrichsen <x-alina@gmx.net>
 # Special thanks to bittorf wireless ))
-START=50
+START=65
 
-OLSRD_OLSRD_SCHEMA='ignore:internal config_file:internal DebugLevel=0 IpVersion=4 AllowNoInt:bool=1 Pollrate=0.025 TcRedundancy=2 MprCoverage=3 LinkQualityFishEye=1 LinkQualityWinSize=100 LinkQualityDijkstraLimit=0+9.0 LinkQualityLevel=2 UseHysteresis:bool=0 FIBMetric=flat ClearScreen:bool=1 Willingness=3 LinkQualityAging=0.1 LinkQualityAlgorithm=etx_ff'
+OLSRD_OLSRD_SCHEMA='ignore:internal config_file:internal DebugLevel=0 AllowNoInt=yes'
 OLSRD_IPCCONNECT_SCHEMA='ignore:internal Host:list Net:list2'
 OLSRD_LOADPLUGIN_SCHEMA='ignore:internal library:internal Host4:list Net4:list2 Host:list Net:list2 Host6:list Net6:list2 Ping:list redistribute:list NonOlsrIf:list name:list lat lon latlon_infile HNA:list2 hosts:list2'
-OLSRD_INTERFACE_SCHEMA='ignore:internal interface:internal AutoDetectChanges:bool Ip4Broadcast=255.255.255.255 HelloInterval=2.0 HelloValidityTime=40.0 TcInterval=5.0 TcValidityTime=100.0 MidInterval=18.0 MidValidityTime=324.0 HnaInterval=18.0 HnaValidityTime=108.0'
+OLSRD_INTERFACE_SCHEMA='ignore:internal interface:internal AutoDetectChanges:bool'
+OLSRD_INTERFACE_DEFAULTS_SCHEMA='AutoDetectChanges:bool'
 
 T='	'
 N='
@@ -26,7 +27,7 @@ validate_ifname() {
 
 validate_olsrd_option() {
 	local str="$1"
-	[ -z "$str" -o "$str" != "${str%%[! 	0-9A-Za-z./:_-]*}" ] && return 1
+	[ -z "$str" -o "$str" != "${str%%[! 	0-9A-Za-z./|:_-]*}" ] && return 1
 	return 0
 }
 
@@ -127,7 +128,7 @@ olsrd_write_option() {
 	fi
 
 	if [ "$value" != "${value%%[G-Zg-z_-]*}" ]; then
-		if [ "$option" != "Ip6AddrType" -a "$value" != "yes" -a "$value" != "no" ]; then
+		if [ "$option" != "Ip6AddrType" -a "$option" != "LinkQualityMult" -a "$value" != "yes" -a "$value" != "no" ]; then
 			value="\"$value\""
 		fi
 	fi
@@ -170,6 +171,19 @@ olsrd_write_plparam() {
 		option="$1"
 		shift
 		value="$*"
+	fi
+	if [ "$option" = 'NonOlsrIf' ]; then
+		if validate_varname "$value"; then
+			if get_ifname "$value"; then
+				ifname="$IFNAME"
+				echo "Info: mdns Interface '$value' ifname '$ifname' found" 1>&2
+			else
+				echo "Warning: mdns Interface '$value' not found, skipped" 1>&2
+			fi
+		else
+			warning_invalid_value olsrd "$cfg" "NonOlsrIf"
+		fi
+		[ -z "$ifname" ] || value=$ifname
 	fi
 
 	echo -n "${N}${param}PlParam \"$option\" \"$value\""
@@ -489,6 +503,17 @@ olsrd_write_interface() {
 	return 0
 }
 
+olsrd_write_interface_defaults() {
+	local cfg="$1"
+	validate_varname "$cfg" || return 0
+
+	echo -n "${N}InterfaceDefaults$ifnames${N}{"
+	config_write_options "$OLSRD_INTERFACE_DEFAULTS_SCHEMA" "$cfg" olsrd_write_option "${T}"
+	echo "${N}}"
+
+	return 1
+}
+
 olsrd_update_schema() {
 	local command="$1"
 	validate_varname "$command" || return 0
@@ -505,6 +530,7 @@ olsrd_update_schema() {
 		IpcConnect) config_update_schema OLSRD_IPCCONNECT_SCHEMA "$command" "$varname" "$value";;
 		LoadPlugin) config_update_schema OLSRD_LOADPLUGIN_SCHEMA "$command" "$varname" "$value";;
 		Interface) config_update_schema OLSRD_INTERFACE_SCHEMA "$command" "$varname" "$value";;
+		InterfaceDefaults) config_update_schema OLSRD_INTERFACE_DEFAULTS_SCHEMA "$command" "$varname" "$value";;
 	esac
 
 	return 0
@@ -524,6 +550,7 @@ olsrd_write_config() {
 	[ "$HNA6_COUNT" -gt 0 ] && echo "${N}}"
 	config_foreach olsrd_write_loadplugin LoadPlugin
 	INTERFACES_COUNT=0
+	config_foreach olsrd_write_interface_defaults InterfaceDefaults
 	config_foreach olsrd_write_interface Interface
 	echo
 
@@ -568,6 +595,7 @@ start() {
 		bindv6only="$(sysctl -n net.ipv6.bindv6only)"
 		sysctl -w net.ipv6.bindv6only=1
 		sed -e 's/^\t\t[0-9.]*[ ][0-9.]*$//' < "$OLSRD_CONFIG_FILE" > /var/etc/olsrd.conf.ipv6
+		sed -i '/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/d' /var/etc/olsrd.conf.ipv6
 		olsrd -f /var/etc/olsrd.conf.ipv6 -nofork < /dev/null > /dev/null &
 
 		sed -e 's/^IpVersion[ ][ ]*6$/IpVersion 4/' -e 's/^\t\t[A-Fa-f0-9.:]*[:][A-Fa-f0-9.:]*[ ][0-9]*$//' < "$OLSRD_CONFIG_FILE" > /var/etc/olsrd.conf.ipv4
